### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by Fiely** [49thSecurityDivision/admin-stuffz#5]
Equipment
https://github.com/orgs/49thSecurityDivision/projects/6#card-7415689
* @trvon everything besides mount
* @49thSecurityDivision/lab-trolls next meeting mount 

Scripts
https://github.com/orgs/49thSecurityDivision/projects/6#card-7415726
* @mfiely see previous issue #1 
* @elreydetoda google sheets

**Comment by elreydetoda** [comment]
did you click on the link?

**Comment by Fiely** [comment]
I have updated the card for clarity @trvon
